# Site settings
title: Grove Pointe HOA
email: admin@grovepointehoa.com
description: > # this means to ignore newlines until "baseurl:"
  News and information for the Grove Pointe Home Owner's Association in Hahira,
  GA.
baseurl: ""
url: "https://grovepointehoa.com"
twitter_username: ''
github_username:  ''
gems:
- jekyll-assets
permalink: /news/:year-:month/:title


# Build settings
markdown: kramdown

exclude: ["lib", "config.rb", ".sass-cache", "Capfile", "config", "log", "Rakefile", "Rakefile.rb", "tmp", "*.sublime-project", "*.sublime-workspace", "Gemfile", "Gemfile.lock", "README.md", "LICENSE", "node_modules", "Gruntfile.js", "package.json"]

assets:
  compress:
    css:  sass
    js:   uglifier
  sources:
    - _assets/images
    - _assets/stylesheets
    - _assets/fonts
    - _assets/js
