# Site settings
title: Grove Pointe HOA
email: your-email@domain.com
description: > # this means to ignore newlines until "baseurl:"
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.
baseurl: "http://dev.brooksgarrett.com" # the subpath of your site, e.g. /blog/
url: "http://nas:8000" # the base hostname & protocol for your site
twitter_username: jekyllrb
github_username:  jekyll
gems:
- jekyll-compass

# Build settings
markdown: kramdown

exclude: ["lib", "config.rb", ".sass-cache", "Capfile", "config", "log", "Rakefile", "Rakefile.rb", "tmp", "*.sublime-project", "*.sublime-workspace", "Gemfile", "Gemfile.lock", "README.md", "LICENSE", "node_modules", "Gruntfile.js", "package.json"]

